### ISSUE TITLE
Frontender blocks li3_docs css

### ISSUE THREAD

**Issue by hans-d** [joseym/li3_frontender#2]
When using Frontender, it blocks the css for `https://github.com/UnionOfRAD/li3_docs` from loading (and prob other plugins as well).

I have it in my libraries.php as `Libraries::add('li3_frontender', array('compress' => false));`

**Comment by joseym** [comment]
Can you provide a gist of the error or stack trace it throws, if any?

iTapped this message on a tiny iScreen.

**Comment by hans-d** [comment]
it just shows a nice 404: stylesheet not found....

stylesheet is located within the plugin webroot, not in the main webroot.

**Comment by joseym** [comment]
Haha, ok. Should have it fixed shortly!

Thanks!

iTapped this message on a tiny iScreen.

**Comment by hans-d** [comment]
You already have a PR...
