### ISSUE TITLE
Installing via git expects libraries in app/libraries

### ISSUE THREAD

**Issue by hans-d** [joseym/li3_frontender#4]
Installing them in the main libraries gives an error...

**Comment by hans-d** [comment]
undocumented feature in bootstrap: `$options =  Libraries::get('li3_frontender') + array('source' => 'composer');`

**Comment by hans-d** [comment]
you've got PR for this... It's a PHP error: 

```
PHP Warning:  require([...]/app/libraries/_source/leafo/lessphp/lessc.inc.php): failed to open stream: No such file or directory in [..]\libraries\lithium\core\Libraries.php on line 332
```

**Comment by joseym** [comment]
PR merged, thanks for catching these and contributing to the fix!

**Comment by hans-d** [comment]
thanks for the added `/`
